import type { ConnectorSchema } from '../types.js';

export const CONFLUENCE_PAGE_SCHEMA: ConnectorSchema = {
  connector: 'confluence',
  entityType: 'confluence_page',
  frontmatterNamespace: 'confluence',
  updateMethod: 'updatePage',
  entityIdField: 'source_ref',
  connectionIdSource: 'item_connectionId',
  fields: [
    {
      markdownField: 'title',
      location: 'body_title',
      apiField: 'title',
      direction: 'readwrite',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'body',
      location: 'block_content',
      apiField: 'body',
      direction: 'readwrite',
      resolution: 'adf_convert',
      valueType: 'string',
    },
    {
      markdownField: 'status',
      location: 'frontmatter',
      apiField: 'status',
      direction: 'readwrite',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'space',
      location: 'frontmatter',
      apiField: 'spaceKey',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'space_name',
      location: 'frontmatter',
      apiField: 'spaceName',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'version',
      location: 'frontmatter',
      apiField: 'version',
      direction: 'read',
      resolution: 'direct',
      valueType: 'number',
    },
    {
      markdownField: 'type',
      location: 'frontmatter',
      apiField: 'type',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'parent_id',
      location: 'frontmatter',
      apiField: 'parentId',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
  ],
};
