import type { ConnectorSchema } from '../types.js';

export const LINEAR_ISSUE_SCHEMA: ConnectorSchema = {
  connector: 'linear',
  entityType: 'linear_issue',
  frontmatterNamespace: 'linear',
  updateMethod: 'updateIssue',
  entityIdField: 'source_ref',
  connectionIdSource: 'item_connectionId',
  fields: [
    {
      markdownField: 'title',
      location: 'body_title',
      apiField: 'title',
      direction: 'readwrite',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'description',
      location: 'body_section',
      apiField: 'description',
      direction: 'readwrite',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'state',
      location: 'frontmatter',
      apiField: 'stateId',
      direction: 'readwrite',
      resolution: 'lookup',
      lookupEntity: 'workflow_state',
      lookupMatchField: 'name',
      valueType: 'string',
    },
    {
      markdownField: 'priority_label',
      location: 'frontmatter',
      apiField: 'priority',
      direction: 'readwrite',
      resolution: 'transform',
      transformFn: 'priorityLabelToNumber',
      valueType: 'string',
    },
    {
      markdownField: 'assignee',
      location: 'frontmatter',
      apiField: 'assigneeId',
      direction: 'readwrite',
      resolution: 'lookup',
      lookupEntity: 'user',
      lookupMatchField: 'name',
      valueType: 'string',
    },
    {
      markdownField: 'due_date',
      location: 'frontmatter',
      apiField: 'dueDate',
      direction: 'readwrite',
      resolution: 'direct',
      valueType: 'date',
    },
    {
      markdownField: 'estimate',
      location: 'frontmatter',
      apiField: 'estimate',
      direction: 'readwrite',
      resolution: 'direct',
      valueType: 'number',
    },
    {
      markdownField: 'tags',
      location: 'frontmatter',
      apiField: 'labelIds',
      direction: 'readwrite',
      resolution: 'lookup',
      lookupEntity: 'label',
      lookupMatchField: 'name',
      valueType: 'string[]',
    },
    {
      markdownField: 'identifier',
      location: 'frontmatter',
      apiField: 'identifier',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'team',
      location: 'frontmatter',
      apiField: 'team',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'creator',
      location: 'frontmatter',
      apiField: 'creator',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'state_type',
      location: 'frontmatter',
      apiField: 'stateType',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
    {
      markdownField: 'branch',
      location: 'frontmatter',
      apiField: 'branchName',
      direction: 'read',
      resolution: 'direct',
      valueType: 'string',
    },
  ],
};
